### ISSUE TITLE
Build out header, navbar, and login page

### ISSUE THREAD

**Issue by ayoung09** [ayoung09/Grace-Shopper#73]

**Comment by siteations** [comment]
hey- i'm trying to avoid overlap in creating product actions. I'll start these sunday - let me know if you have already handled any of them in the nav-bar features creation:

//-------------------- product related actions ----------------------------
/*  load all products . . . to show on front page for non-authenticated, non-session new users
    many-filter products . . . based on the nav bar categories passed in, filter all products through 1 or more matches 
    one-filter products . . . typed in search from home screen - exact or partial match - no preset categories
    get user-products-cart . . . if logged-in, from cookie-cart session 
    get user-products-history . . . if logged-in, from purchasing history 
    select product . . . focused product from click interaction - single page product display
    create product . . . brewer creates/adds product
      get related products - maybe not necessary - just run through the many-filter to get like brew & flavor...the 'you might also like' feature in amazon
    
    other?
    
*/
